### ISSUE TITLE
Comparison to tinyformat and cppformat

### ISSUE THREAD

**Issue by rigtorp** [rnlf/flossy#1]
What are the advantages of flossy compared to https://github.com/c42f/tinyformat and https://github.com/cppformat/cppformat?

**Comment by rnlf** [comment]
Well,

tbh I have not checked any of these. Both seem to be fine at first 
glance. I have not done any benchmarks or anything. cppformat doesn't 
seem to be header-only, tinyformat seems to be a bit bigger than flossy.

I plan to do some benchmarks and see if flossy is in the same 
performance range as the two, but for now, it's just a library I wanted 
to make and use in my own projects.

Cheers,
rnlf

**Comment by rigtorp** [comment]
Ok, thanks!
